image: ubuntu
env:
  - DEBIAN_FRONTEND=noninteractive
script:
  - apt-get update
  - apt-get install -y build-essential
  - apt-get install -y supervisor
  - apt-get install -y mysql-server
  - apt-get install -y wget
  - apt-get install -y unzip
  - apt-get install -y php5-cli php5-json php5-mysql
  - apt-get install -y ruby2.0 ruby2.0-dev
  - apt-get install -y libxslt-dev libxml2-dev
  - apt-get install -y curl

  # Fix ruby
  - rm /usr/bin/ruby
  - rm /usr/bin/gem
  - ln -s /usr/bin/ruby2.0 /usr/bin/ruby
  - ln -s /usr/bin/gem2.0 /usr/bin/gem

  # Fix mysql/gem
  - ln -s /var/run/mysqld/mysqld.sock /tmp/mysql.sock

  # Composer
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

  # Install wp-cli and allow root to use it
  - wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -O /usr/local/bin/wp.orig
  - chmod 755 /usr/local/bin/wp.orig
  - echo '#!/bin/sh' > /usr/local/bin/wp
  - echo 'exec wp.orig --allow-root $@' >> /usr/local/bin/wp
  - chmod 755 /usr/local/bin/wp

  - gem install rspec httparty nokogiri ruby-mysql

  # Create db
  - service mysql start
  - mysql -e 'CREATE DATABASE oauth2servertest'

  - composer install

  - make test
