build:
  image: thedxw/wordpress-test
  commands:
    # Make it possible to execute builds on vboxsf filesystems
    - cp -r . /build2
    - cd /build2

    # Bundler
    - sh -c 'cd tests && bundle install'

    # Create db
    - service mysql start
    - mysql -e 'CREATE DATABASE oauth2servertest'

    # Test
    - make test
